### ISSUE TITLE
"segmentation fault (core dumped) " after run QuickView

### ISSUE THREAD

**Issue by WangYun1995** [alejandrobll/py-sphviewer#27] opened 2021-03-03 01:42 UTC
Hi @alejandrobll,

I wrote a python script to test the functionalities of `QuickView` after installing py-sphviewer on the Linux server of my team.

The code snippet is shown below
```Python
import numpy as np
import matplotlib as mpl
mpl.use("Agg")
import matplotlib.pyplot as plt
from sphviewer.tools import QuickView

with open("/home2/TNG100-1/postprocessing/dm_poscut_z0_alpha.dat") as ff:
    dm_pos = np.fromfile(ff, dtype='float32').reshape((3,80727093), order="F")

dm_pos = (dm_pos.transpose()) / 1000.0

QuickView(dm_pos, r="infinity", plot=False)
projection.imsave("test_sphviewer.png", bbox_inches="tight")
```
After typing `ipython test_sphviewer.py` on the command line, It returned to me `Segmentation fault (core dumped)`.
Can you help me with this issue?

**Comment by alejandrobll** [comment] 2021-03-03 08:28
Could you please provide a minimal working example that reproduces the issue? Using some dummy particle distribution? I cannot  test your code. 

Please also consider running the few examples provided, and try to adapt those to your problem.

**Comment by WangYun1995** [comment] 2021-03-03 13:29
`dm_pos` are coordinates of dark matter particles selected from TNG100-1 data at redshift 0.0. And the selection criteria is 25000.0 kpc/h <= x, y, z <= 45000.0 kpc/h.

**Comment by alejandrobll** [comment] 2021-03-03 13:35
Unfortunately, this information is not useful to reproduce your error.

**Comment by WangYun1995** [comment] 2021-03-03 13:57
Hi, 

To check or reproduce my error, I downloaded the hdf5 file i.e. darkmatter_box.h5py from the home page of py-sphviewer.
Then I run the example shown below.
```Python
import numpy as np
import matplotlib as mpl
mpl.use("Agg")
import matplotlib.pyplot as plt

import h5py
from sphviewer.tools import QuickView

with h5py.File('darkmatter_box.h5py','r') as f:
    pdrk = f['PartType1/Coordinates'][()]

projection=QuickView(pdrk, r="infinity", plot=False)
projection.imsave("test_sphviewer.png")
```

There is no 'Segmentation fault' this time. But, it returns `Error while saving image` to me.

**Comment by alejandrobll** [comment] 2021-03-03 14:10
This works for me using the latest version. Please check that you have write permissions where you would like to save the image.

**Comment by WangYun1995** [comment] 2021-03-03 14:15
When I changed the file name i.e. "test_sphviewer.png" to a complete file path,  the issue of `Error while saving image` was solved and the image was saved successfully.

**Comment by WangYun1995** [comment] 2021-03-03 14:20
I noticed that the number of particles of  'darkmatter_box.h5py' is far less than 80727093, i.e. the number of particles in my example. 

Did the big data cause the segmentation fault?

**Comment by alejandrobll** [comment] 2021-03-24 15:27
No, this shouldn't produce a segmentation fault. Have you solved the problem?

**Comment by AshKelly** [comment] 2021-03-24 20:13
@alejandrobll  could this be caused by `pykdtree` failing because of the large amount of particles?

@WangYun1995 could you try the following script,

```
import numpy as np
import matplotlib as mpl
mpl.use("Agg")
import matplotlib.pyplot as plt
from sphviewer.tools import QuickView
from pykdtree.kdtree import KDTree

with open("/home2/TNG100-1/postprocessing/dm_poscut_z0_alpha.dat") as ff:
    dm_pos = np.fromfile(ff, dtype='float32').reshape((3,80727093), order="F")

dm_pos = (dm_pos.transpose()) / 1000.0

print("Calculating smoothing lengths")
nb = 64
tree = KDTree(dm_pos)
d, idx = tree.query(dm_pos, k=nb)
hsml = d[:, nb - 1]
print("Done.")

projection=QuickView(dm_pos, hsml=hsml, r="infinity", plot=False)
QuickView(dm_pos, r="infinity", plot=False)
projection.imsave("test_sphviewer.png", bbox_inches="tight")
```

I suspect this will error before printing `Done.`

**Comment by alejandrobll** [comment] 2021-03-24 23:15
I don't think this would lead to a segmentation fault. It might give the wrong answer, but still an answer.

**Comment by WangYun1995** [comment] 2021-03-25 02:04
It seems that ```QuickView``` does not support the Fortran unformatted file, such as 'dm_poscut_z0_alpha.dat'.  "Segmentation fault" was solved after I replaced the Fortran unformatted file with the HDF5 file.

However, ```QuickView``` is too slow when the number of particles ~10^9.

**Comment by AshKelly** [comment] 2021-03-25 09:00
Ah! Could this be caused by the contiguity of the array? When you load from a fortran file the contiguity is different to that expected in C. This could definitely cause a segault if the array is assumed to be C contiguous.

You could try
```
dm_pos = np.ascontiguousarray(dm_pos)
```
before the `QuickView`. I suspect with this the segault will disappear - but, I'm not sure how @alejandrobll deals with the arrays. This might not make a difference!

PS: Could it be the `malloc`'s in `scenemodule.c` inside `get_float_array` and `get_double_array` that failed to allocate and thus, are `null`? I'm not sure how worried you are about actually de-bugging this!

**Comment by alejandrobll** [comment] 2021-04-01 09:30
I would like to see if this solves the problem, although the code explicitly enforces C-contiguous arrays - and convert the arrays to C-contiguous if they are not -. If this solves the problem I might need to revise how the conversion is done in the NumPy C-API.
Regarding the malloc in `scenemodule`, I agree. If the previous line that enforces contiguity of the array fails, then this might give a segmentation fault. I would need to have a minimal example that produces a segmentation fault to debug this. 
Thanks!

**Comment by WangYun1995** [comment] 2021-04-22 02:51
Hi, @alejandrobll

To give a minimal example, I have sent the data needed to you by email titled " Data for a minimal example that produces a segmentation fault".

Combined with this data and code snippet shown below,  you can reproduce a segmentation fault.

```Python
import numpy as np
import matplotlib.pyplot as plt
from sphviewer.tools import QuickView


with open("dm_poscut_z0_alpha.dat") as ff:
    dm_pos = np.fromfile(ff, dtype='float32').reshape((3,80727093), order="F")

dm_pos = dm_pos.astype(np.float64)

dm_pos = (dm_pos.transpose()) / 1000.0  # kpc to Mpc

projection = QuickView(dm_pos, r="infinity", plot=False)

projection.imsave("test_sphviewer.png")
```

**Comment by alejandrobll** [comment] 2021-04-22 14:18
I could not reproduce the segmentation fault with your example. The code produced an output without errors, although I executed it with np.float32 rather than np.float64. Any good reason to go from float32 to np.float64? I attach the picture produced by your code and the data you shared by email.

Could you please try compiling the latest version of the code and perform a fresh installation again? This might help. 

Given that I cannot reproduce your error with the latest version of the code, I will close the issue. Feel free to open a new issue if the problem persists and you identify another example.

Thanks,
Alejandro

![image](https://user-images.githubusercontent.com/7341581/115729901-b7833180-a37d-11eb-971e-3e7f5c282d13.png)

**Closed as completed** 2021-04-22 17:35 UTC
